Repository Bluekey-Payment-System/BPS-FE, pull requests merged in 2023-09, with the labels that each got.

#110 BPS-267/내 프로필 페이지 프로필 정보 수정 api, 비밀번호 재설정 api 연동
  src/components/auth/ChangePasswordForm/CurrentPasswordForm/CurrentPasswordForm.tsx
  src/components/auth/ChangePasswordForm/NewPasswordForm/NewPasswordForm.tsx
  src/components/my-profile/AdminProfileForm/AdminProfileForm.tsx
  src/components/my-profile/ArtistProfileForm/ArtistProfileForm.tsx
  src/pages/admin/my-profile/index.page.tsx
  src/pages/artists/[artistId]/my-profile/index.page.tsx
  src/redux/store.ts
  src/services/api/requests/artist/artist.patch.api.ts
  src/services/api/requests/auth/auth.patch.api.ts
  src/services/queries/auth/useChangePassword.ts
  src/services/queries/auth/useConfirmPassword.ts
  src/services/queries/my-profile/useUpdateProfile.ts
  src/types/dto.ts
  src/utils/test.utils.tsx
Labels: 🚀 feature

#111 BPS-185/토스트 컴포넌트 리뉴얼
  src/components/common/Toast/Toast.module.scss
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastPortal.tsx
  src/components/common/Toast/ToastRoot.tsx
  src/hooks/useToast.ts
  src/redux/slices/toastSlice.ts
  src/types/enums/toast.enum.ts
Labels: 🚀 feature, 🛠️ fix, 🎨 design

#112 BPS-296/정산 업로드 경고 내역 다운로드 기능 추가
  package.json
  src/components/upload-revenue/AlertDataTable/AlertDataTable.tsx
  src/components/upload-revenue/AlertDataTable/AlertDataTable.utils.ts
  src/components/upload-revenue/UploadRevenueAlertModal/UploadRevenueAlertModal.tsx
  src/constants/alertDataHeaders.ts
  src/services/api/types/errors.ts
  src/services/queries/upload-revenue/useRevenueUploadHistory.ts
  yarn.lock
Labels: 🚀 feature

#115 BPS-141/도커를 사용한 CICD 스크립트 추가(데브 서버용)
  .dockerignore
  .github/workflows/dev-cicd.yml
  Makefile
  docker/development/Dockerfile
  docker/development/docker-compose.yml
  docker/local/Dockerfile
  docker/local/docker-compose.yml
  docker/production/Dockerfile
  docker/production/docker-compose.yml
  next.config.js
  package.json
  yarn.lock
Labels: 🧹chore, 🐌 priority: low

#113 BPS-312/필터 모달 UI퍼블리싱
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/Filter/Filter.module.scss
  src/components/common/Filter/Filter.tsx
  src/components/common/Filter/FilterForm/FilterForm.module.scss
  src/components/common/Filter/FilterForm/FilterForm.tsx
  src/components/common/Filter/FilterForm/MultiRangeSlider.module.scss
  src/components/common/Filter/FilterForm/MultiRangeSlider.tsx
  src/components/common/Filter/FilterForm/MultiRangeSlider.util.ts
  src/styles/globals.scss
Labels: 🚀 feature

#116 docs: test
  README.md
Labels: ✅ test

#120 BPS-318/ README 작성
  README.md
Labels: 📝 docs

#121 BPS-351/타 계정 관리 기능 추가
  src/components/manage-accounts/AdminAccountsTable/AdminAccountsTable.tsx
  src/components/manage-accounts/ArtistAccountsTable/ArtistAccountsTable.tsx
  src/components/manage-accounts/PasswordReissueModal/ReissuedPasswordModal.tsx
  src/services/api/requests/auth/auth.delete.api.ts
  src/services/api/requests/auth/auth.patch.api.ts
  src/services/api/types/auth.ts
  src/services/queries/auth/useReissuePassword.ts
  src/services/queries/manage-accounts/useUpdateArtistProfile.ts
  src/services/queries/manage-accounts/useWithdrawMember.ts
  src/types/dto.ts
Labels: 🚀 feature
