Repository Bluekey-Payment-System/BPS-FE, pull requests merged in 2023-08, with the labels that each got.

#1 BPS-15/프로그래스 바 컴포넌트 제작
  src/components/ProgressBar/ProgressBar.module.scss
  src/components/ProgressBar/ProgressBar.tsx
  src/pages/_app.page.tsx
  src/pages/_document.page.tsx
  src/types/global.d.ts
Labels: 🚀 feature

#2 BPS-18/dropdown 타입 1번 제작
  public/images/dropdown-down.svg
  public/images/dropdown-up.svg
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownList.tsx
  src/components/common/Dropdown/DropdownSelectedValue.tsx
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/Dropdown/DropdownUI.tsx
  src/components/common/ProgressBar/ProgressBar.module.scss
  src/components/common/ProgressBar/ProgressBar.tsx
  src/hooks/useOutsideClick.ts
  src/pages/tony.page.tsx
Labels: 🚀 feature

#3 BPS-17/Chip 컴포넌트 제작
  src/components/common/Chip/Chip.module.scss
  src/components/common/Chip/Chip.tsx
  src/styles/_variables.scss
Labels: 🚀 feature

#7 BPS-36/일반 버튼 컴포넌트 & 금액 포맷 함수 제작
  src/components/common/CommonBtns/Button/Button.module.scss
  src/components/common/CommonBtns/Button/Button.tsx
  src/pages/ian.page.tsx
  src/utils/utilFormatMoney.ts
Labels: 🚀 feature

#5 BPS-48/input 기능이 추가된 드롭다운 제작
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownList.tsx
  src/components/common/Dropdown/DropdownSelectedValue.tsx
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/Dropdown/DropdownUI.tsx
  src/components/common/Dropdown/DropdownWithInput/DropdownListWithInput.tsx
  src/pages/tony.page.tsx
Labels: 🚀 feature

#4 BPS-38/토스트 컴포넌트 추가
  .eslintrc.json
  next.config.js
  package.json
  public/images/lightening.png
  src/components/common/Toast/Toast.module.scss
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastPortal.tsx
  src/components/common/Toast/ToastRoot.tsx
  src/components/common/Toast/__tests__/Toast.test.tsx
  src/hooks/useToast.ts
  src/pages/__tests__/index.test.tsx
  src/pages/_app.page.tsx
  src/pages/_document.page.tsx
  src/redux/slices/toastSlice.ts
  src/redux/store.ts
  src/styles/globals.scss
  src/utils/test.utils.tsx
  yarn.lock
Labels: 🚀 feature, 🧹chore

#6 BPS-33/Custom Legend 컴포넌트
  src/components/common/CustomLegend/CustomLegend.module.scss
  src/components/common/CustomLegend/CustomLegend.tsx
  src/pages/tony.page.tsx
Labels: 🚀 feature, 🙏 sorry

#9 BPS-19/ChipButton 컴포넌트 제작
  src/components/common/CommonBtns/Button/Button.tsx
  src/components/common/CommonBtns/ChipButton/ChipButton.module.scss
  src/components/common/CommonBtns/ChipButton/ChipButton.tsx
  src/pages/ian.page.tsx
Labels: 🚀 feature

#10 BPS-14/Tooltip 컴포넌트 제작
  src/components/common/Chip/Chip.tsx
  src/components/common/Tooltip/Tooltip.module.scss
  src/components/common/Tooltip/Tooltip.tsx
  src/components/common/Tooltip/TooltipPortal.tsx
  src/components/common/Tooltip/TooltipRoot.tsx
  src/components/common/Tooltip/getPosition.tsx
  src/pages/_document.page.tsx
  src/pages/alice.page.tsx
Labels: 🚀 feature

#12 BPS-29/Emptydata 컴포넌트 제작
  public/images/empty-data.svg
  public/images/empty-search-result.svg
  src/components/common/EmptyData/EmptyData.module.scss
  src/components/common/EmptyData/EmptyData.tsx
  src/pages/alice.page.tsx
Labels: 🚀 feature

#14 refactor - Tooltip 컴포넌트 util 컨벤션 수정
  src/components/common/Tooltip/Tooltip.utils.ts
  src/components/common/Tooltip/TooltipRoot.tsx
Labels: ♻️ refactor

#13 BPS-58/Popover 컴포넌트 추가
  src/components/common/Popover/Popover.tsx
  src/components/common/Popover/__tests__/Popover.test.tsx
  src/hooks/useOutsideClick.ts
Labels: 🚀 feature

#15 BPS-22/페이지네이션 컴포넌트 제작
  public/images/page-ellipsis.svg
  src/components/common/Pagination/Pagination.tsx
  src/components/common/Pagination/PaginationArrowUI.module.scss
  src/components/common/Pagination/PaginationArrowUI.tsx
  src/components/common/Pagination/PaginationUI.module.scss
  src/components/common/Pagination/PaginationUI.tsx
  src/constants/pagination.tsx
  src/pages/ian.page.tsx
  src/utils/utilUpdateQueryParam.ts
Labels: 🚀 feature

#18 BPS-70-Tooltip ellipsis 확인 로직 추가
  src/components/common/Tooltip/Tooltip.utils.ts
  src/components/common/Tooltip/TooltipRoot.tsx
Labels: 🚀 feature

#11 BPS-30/검색바 컴포넌트 제작 및 드롭다운 디자인 변경
  public/images/search-bar.svg
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownList.tsx
  src/components/common/Dropdown/DropdownSelectedValue.tsx
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/Dropdown/DropdownUI.tsx
  src/components/common/Dropdown/DropdownWithSearchBar/DropdownListWithSearchBar.tsx
  src/components/common/ProgressBar/ProgressBar.tsx
  src/components/common/SearchBar/SearchBar.module.scss
  src/components/common/SearchBar/SearchBar.tsx
  src/pages/tony.page.tsx
  src/styles/_variables.scss
Labels: 🚀 feature, 🎨 design

#17 BPS-60/막대 차트 컴포넌트 제작
  package.json
  src/components/common/Chart/BarChart/BarChart.module.scss
  src/components/common/Chart/BarChart/BarChart.tsx
  src/components/common/Chart/BarChart/BarChart.utils.ts
  src/components/common/Chart/BarChart/BarItem.tsx
  src/utils/utilFormatMoney.ts
  yarn.lock
Labels: 🚀 feature

#19 BPS-28/대시보드 카드 컴포넌트 제작
  src/components/common/Chip/Chip.module.scss
  src/components/common/Chip/Chip.tsx
  src/components/common/DashboardCard/DashboardCard.module.scss
  src/components/common/DashboardCard/DashboardCard.tsx
  src/constants/pagination.ts
  src/pages/ian.page.tsx
Labels: 🚀 feature

#24 BPS-86/Layouts 컴포넌트 제작
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/Layouts/MainLayout.module.scss
  src/components/common/Layouts/MainLayout.tsx
  src/components/common/Layouts/MainLayoutWithDropdown.module.scss
  src/components/common/Layouts/MainLayoutWithDropdown.tsx
  src/components/common/Layouts/SectionLayout.module.scss
  src/components/common/Layouts/SectionLayout.tsx
Labels: 🚀 feature, 🎨 design, ❓question

#22 BPS-34/AlbumCard 컴포넌트 제작
  next.config.js
  public/images/default-album-cover.svg
  public/images/kebab.svg
  src/components/common/AlbumCard/AlbumCard.module.scss
  src/components/common/AlbumCard/AlbumCard.tsx
  src/components/common/AlbumCard/OptionsButton.module.scss
  src/components/common/AlbumCard/OptionsButton.tsx
  src/hooks/useOutsideClick.ts
  src/pages/alice.page.tsx
Labels: 🚀 feature, ❓question

#23 BPS-16/Input 컴포넌트 그룹 추가
  .eslintignore
  package.json
  src/components/common/Inputs/Input.util.ts
  src/components/common/Inputs/InputLayout.module.scss
  src/components/common/Inputs/InputLayout.tsx
  src/components/common/Inputs/PasswordInput/EyeToggler.tsx
  src/components/common/Inputs/PasswordInput/PasswordField.tsx
  src/components/common/Inputs/TextField.module.scss
  src/components/common/Inputs/TextField/TextField.tsx
  src/components/common/Inputs/TextFieldWithCopy/TextFieldWithCopy.tsx
  src/components/common/Inputs/TextFieldWithMaxBytes/TextFieldWithMaxBytes.tsx
  src/components/common/Inputs/TextFieldWithUnit/TextFieldWithUnit.tsx
  src/components/common/Inputs/__tests__/Inputs.test.tsx
  src/hooks/useForwardRef.ts
  src/hooks/useInputWithEditMode.ts
  src/pages/kenny.page.tsx
  src/utils/getStringBytes.ts
  yarn.lock
Labels: 🚀 feature, 👀 attention needed, 🙏 sorry

#21 BPS-72/꺾은선 차트 제작
  package.json
  src/components/common/Chart/LineChart/LineChart.tsx
  src/components/common/Chart/LineChart/LineChart.types.ts
  src/components/common/Chart/LineChart/LineChart.utils.ts
  src/components/common/Chart/chart.utils.ts
  src/pages/tony.page.tsx
  yarn.lock
Labels: 🚀 feature, ❓question

#25 BPS-31/ExcelFileUploader 컴포넌트 제작
  public/images/upload.svg
  src/components/common/ExcelFileUploader/ExcelFileUploader.module.scss
  src/components/common/ExcelFileUploader/ExcelFileUploader.tsx
  src/pages/alice.page.tsx
Labels: 🚀 feature, 🙏 sorry

#26 BPS-35/Checkbox 컴포넌트 추가
  src/components/common/Inputs/Checkbox/Checkbox.module.scss
  src/components/common/Inputs/Checkbox/Checkbox.tsx
  src/components/common/Inputs/__tests__/Inputs.test.tsx
Labels: 🚀 feature

#28 BPS-27/공통 모달 컴포넌트
  src/components/common/Modals/AlertModal/AlertModal.module.scss
  src/components/common/Modals/AlertModal/AlertModal.tsx
  src/components/common/Modals/AlertModal/AlertModalRoot.tsx
  src/components/common/Modals/Modal.module.scss
  src/components/common/Modals/Modal.tsx
  src/hooks/useAlertModal.ts
  src/pages/_app.page.tsx
  src/pages/kenny.page.tsx
  src/redux/slices/alertModalSlice.ts
  src/redux/store.ts
  src/types/enums/modal.enum.ts
Labels: 🚀 feature, 🚨 priority: high

#27 BPS-102/ dto type 제작
  src/types/dto.ts
  src/types/enums/user.enum.ts
Labels: 🚀 feature

#30 BPS-21/테이블 컴포넌트 제작
  src/components/common/Chart/BarChart/BarChart.tsx
  src/components/common/Chart/LineChart/LineChart.tsx
  src/components/common/DashboardCard/DashboardCard.tsx
  src/components/common/Pagination/PaginationUI.tsx
  src/components/common/ProgressBar/ProgressBar.module.scss
  src/components/common/Table/Assemble/AdminAccountsTable.tsx
  src/components/common/Table/Assemble/TrackStatusTable.module.scss
  src/components/common/Table/Assemble/TrackStatusTable.tsx
  src/components/common/Table/Assemble/UnRegisteredDataTable.tsx
  src/components/common/Table/Composition/TableBodyUI.tsx
  src/components/common/Table/Composition/TableCellUI.module.scss
  src/components/common/Table/Composition/TableCellUI.tsx
  src/components/common/Table/Composition/TableContainerUI.module.scss
  src/components/common/Table/Composition/TableContainerUI.tsx
  src/components/common/Table/Composition/TableHeaderUI.module.scss
  src/components/common/Table/Composition/TableHeaderUI.tsx
  src/components/common/Table/Composition/TableRowUI.module.scss
  src/components/common/Table/Composition/TableRowUI.tsx
  src/components/common/Tooltip/Tooltip.utils.ts
  src/components/common/Tooltip/TooltipRoot.tsx
  src/constants/mock.ts
  src/constants/table.ts
  src/pages/ian.page.tsx
  src/types/dto.temp.ts
  src/utils/formatMoney.ts
  src/utils/throttle.ts
  src/utils/updateQueryParam.ts
Labels: 🚀 feature, 🙏 sorry

#31 BPS-23/GNB 컴포넌트 제작
  public/images/bell.svg
  public/images/bluekey-music-insight-logo.svg
  public/images/hamburger.svg
  public/images/logo.svg
  public/images/logout.svg
  src/components/layout/GNB/GNB.tsx
  src/components/layout/GNB/MobileGNB.module.scss
  src/components/layout/GNB/MobileGNB.tsx
  src/components/layout/GNB/PCGNB.module.scss
  src/components/layout/GNB/PCGNB.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Layout.types.ts
  src/constants/randomProfileList.ts
Labels: 🚀 feature, 🙏 sorry

#34 BPS-117/사이드 네브 이넘 변경
  src/components/common/Drawer/Drawer.module.scss
  src/components/layout/GNB/GNB.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Layout.types.ts
  src/components/layout/SideNav/SideNav.module.scss
  src/components/layout/SideNav/SideNav.tsx
  src/constants/sidenavList.ts
  src/pages/_app.page.module.scss
  src/pages/_app.page.tsx
  src/redux/slices/userSlice.ts
  src/styles/globals.scss
  yarn.lock
Labels: 🎨 design, 🧹chore

#36 BPS-118/아트보드, 섹션 구분선 레이아웃 컴포넌트 제작
  src/components/common/Layouts/ArtboardLayout.module.scss
  src/components/common/Layouts/ArtboardLayout.tsx
  src/components/common/Layouts/SectionHr.module.scss
  src/components/common/Layouts/SectionHr.tsx
  src/components/common/Layouts/SectionLayout.module.scss
  src/components/layout/SideNav/SideNav.module.scss
  src/components/layout/SideNav/SideNav.tsx
  src/pages/_app.page.tsx
  src/pages/ian.page.tsx
Labels: 🚀 feature

#35 BPS-120/jsdoc 수정
  src/components/common/Chart/DoughnutChart/DoughnutChart.tsx
  src/components/common/Chart/LineChart/LineChart.tsx
  src/components/common/Drawer/Drawer.tsx
  src/components/common/Dropdown/Dropdown.tsx
Labels: 📝 docs

#37 BPS-119/react query 보일러 플레이트 제작 & 샘플 추가
  src/constants/queryKeys.ts
  src/pages/_app.page.tsx
  src/pages/react-query-test.page.tsx
  src/services/queries/useTest.ts
Labels: 🚀 feature

#38 BPS-95/어드민, 아티스트 로그인 페이지 추가
  public/favicon.ico
  public/images/gradient.png
  src/components/auth/SigninForm.module.scss
  src/components/auth/SigninForm.tsx
  src/components/common/Inputs/TextField.module.scss
  src/components/layout/AuthPageLayout.module.scss
  src/components/layout/AuthPageLayout.tsx
  src/components/layout/SideNav/SideNav.module.scss
  src/pages/_app.page.tsx
  src/pages/admin/signin.page.tsx
  src/pages/admin/signin/__tests__/index.test.tsx
  src/pages/admin/signin/index.page.tsx
  src/pages/signin/__tests__/index.test.tsx
  src/pages/signin/index.page.tsx
  src/redux/slices/userSlice.ts
  src/utils/getLatestYearMonthString.ts
Labels: 🚀 feature

#33 BPS-26/MonthPicker 컴포넌트 추가
  public/images/btn-close-normal.svg
  src/components/common/AlbumCard/OptionsButton.tsx
  src/components/common/Dropdown/DropdownHandleUI.module.scss
  src/components/common/Dropdown/DropdownHandleUI.tsx
  src/components/common/MonthPicker/MonthPicker.module.scss
  src/components/common/MonthPicker/MonthPicker.tsx
  src/components/common/MonthPicker/MonthPicker.type.ts
  src/components/common/MonthPicker/MonthPicker.util.ts
  src/components/common/MonthPicker/MonthPickerDropdown.module.scss
  src/components/common/MonthPicker/MonthPickerDropdown.tsx
  src/components/common/MonthPicker/PickerItem.module.scss
  src/components/common/MonthPicker/PickerItem.tsx
  src/components/common/MonthPicker/PickerItemList.module.scss
  src/components/common/MonthPicker/PickerItemList.tsx
  src/components/common/Popover/Popover.tsx
  src/components/common/Popover/__tests__/Popover.test.tsx
  src/constants/monthPicker.ts
  src/hooks/useOutsideClick.ts
  src/pages/kennytest/[month]/index.page.tsx
  src/redux/store.ts
  src/utils/getLastSegmentFromUrl.ts
  src/utils/getMonthFromUrl.ts
  src/utils/getParentPathFromUrl.ts
  src/utils/getYearFromUrl.ts
  src/utils/test.utils.tsx
Labels: 🚀 feature, 🛠️ fix, 🙏 sorry

#40 BPS-133/전체 레이아웃 스타일링 변경
  src/components/common/Layouts/MainLayout.module.scss
  src/components/common/Layouts/MainLayoutWithDropdown.module.scss
  src/components/common/Table/Composition/TableContainerUI.module.scss
  src/components/layout/Layout.module.scss
  src/components/layout/Layout.tsx
  src/components/layout/SideNav/SideNav.module.scss
  src/components/layout/SideNav/SideNav.tsx
  src/components/layout/SideNav/SideNavMobile.tsx
  src/pages/_app.page.tsx
  src/styles/_mixins.scss
  src/styles/globals.scss
Labels: 🎨 design, 🚨 priority: high

#43 BPS-132/모바일 GNB 에러 수정
  src/components/layout/GNB/MobileGNB.module.scss
Labels: 🐛 bug

#41 BPS-121/대시보드 페이지 - 카드리스트, 테이블 컴포넌트 제작
  src/components/common/DashboardCard/DashboardCard.tsx
  src/components/common/DashboardCard/DashboardCard.type.ts
  src/components/common/Table/Assemble/TrackStatusTable.module.scss
  src/components/common/Table/Assemble/TrackStatusTable.tsx
  src/components/common/Table/Composition/TableContainerUI.module.scss
  src/components/common/Table/Composition/TableContainerUI.tsx
  src/components/dashboard/DashboardCardList/DashboardCardList.module.scss
  src/components/dashboard/DashboardCardList/DashboardCardList.tsx
  src/components/dashboard/TrackStatusTable/TrackStatusTable.module.scss
  src/components/dashboard/TrackStatusTable/TrackStatusTable.tsx
  src/pages/ian.page.tsx
  src/pages/ian/202308.page.tsx
Labels: 🚀 feature, 🎨 design

#42 BPS-96/어드민 회원가입 페이지 추가
  src/components/auth/SigninForm.tsx
  src/components/auth/SigninForm/SigninForm.module.scss
  src/components/auth/SigninForm/SigninForm.tsx
  src/components/auth/SignupForm/SignupForm.tsx
  src/components/common/Inputs/TextField.module.scss
  src/components/layout/AuthPageLayout.module.scss
  src/pages/admin/signin/index.page.tsx
  src/pages/admin/signup/index.page.tsx
  src/pages/signin/index.page.tsx
  src/types/enums/user.enum.ts
  src/utils/getLastSegmentFromUrl.ts
  src/utils/getLatestYearMonthString.ts
  src/utils/getMonthFromUrl.ts
  src/utils/getParentPathFromUrl.ts
  src/utils/getYearFromUrl.ts
Labels: 🚀 feature

#45 BPS-32/ImageUploader 컴포넌트 추가
  public/images/upload-small.svg
  src/components/common/ImageUploader/ImageUploader.module.scss
  src/components/common/ImageUploader/ImageUploader.tsx
  src/pages/kenny.page.tsx
Labels: 🚀 feature, 🚨 priority: high, 🙏 sorry

#39 BPS-129/MonthlyTrendsChart 컴포넌트 제작
  src/components/auth/SigninForm.module.scss
  src/components/auth/SigninForm.tsx
  src/components/common/Chart/BarChart/BarChart.tsx
  src/components/common/Chart/BarChart/BarChart.types.ts
  src/components/common/Chart/BarChart/BarChart.utils.ts
  src/components/common/CustomLegend/CustomLegend.tsx
  src/components/dashboard/MonthlyTrendsChart/MonthlyTrendsChart.module.scss
  src/components/dashboard/MonthlyTrendsChart/MonthlyTrendsChart.tsx
  src/services/api/types/admin.ts
Labels: 🚀 feature

#46 BPS-136/dropdown styling 변경
  src/components/common/Dropdown/DropdownSelectedValue.tsx
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/Dropdown/DropdownUI.tsx
  src/components/common/SearchBar/SearchBar.module.scss
  src/components/common/SearchBar/SearchBar.tsx
Labels: 🚀 feature

#47 BPS-131/dought chart 카드 컴포넌트 제작
  src/components/common/Chart/DoughnutChart/DoughnutChart.tsx
  src/components/common/Chart/DoughnutChart/DoughnutChart.types.ts
  src/components/common/Chart/DoughnutChart/DoughnutChart.utils.ts
  src/components/common/CustomLegend/CustomLegend.module.scss
  src/components/common/CustomLegend/CustomLegend.tsx
  src/components/dashboard/TopFiveChart/TopFiveChart.module.scss
  src/components/dashboard/TopFiveChart/TopFiveChart.tsx
  src/components/dashboard/TopFiveChart/TopFiveChart.utils.ts
  src/components/dashboard/TopFiveChart/TopFiveChartLegend.tsx
  src/pages/tony.page.tsx
  src/services/api/types/admin.ts
Labels: 🚀 feature

#49 BPS-144/트랙별 금액 추이 컴포넌트 제작
  src/components/common/Chart/LineChart/LineChart.tsx
  src/components/common/Chart/LineChart/LineChart.types.ts
  src/components/common/Chart/LineChart/LineChart.utils.ts
  src/components/common/Dropdown/DropdownSelectedValue.tsx
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/dashboard/AlbumTrendsChart/AlbumTrendsChart.module.scss
  src/components/dashboard/AlbumTrendsChart/AlbumTrendsChart.tsx
  src/pages/tony.page.tsx
Labels: 🚀 feature

#50 BPS-97/아티스트 등록 페이지 추가
  src/components/auth/SignupForm/SignupForm.tsx
  src/components/common/ImageUploader/ImageUploader.module.scss
  src/components/common/Inputs/InputLayout.module.scss
  src/pages/admin/artists/new/index.module.scss
  src/pages/admin/artists/new/index.page.tsx
  src/pages/admin/artists/new/index.utils.ts
  src/types/artist.types.ts
Labels: 🚀 feature, 🛠️ fix

#52 BPS-151/어드민 대시보드 페이지 UI 제작
  src/components/common/MonthPicker/MonthPicker.module.scss
  src/components/dashboard/MonthlyTrendsChart/MonthlyTrendsChart.module.scss
  src/components/dashboard/TopFiveChart/TopFiveChart.utils.ts
  src/components/layout/Layout.module.scss
  src/constants/mock.ts
  src/pages/admin/dashboard/[month]/index.module.scss
  src/pages/admin/dashboard/[month]/index.page.tsx
Labels: 🚀 feature

#57 BPS-165/앨범 정보 보기의 트랙 리스트 테이블 제작
  src/components/dashboard/TrackListTable/TrackListTable.module.scss
  src/components/dashboard/TrackListTable/TrackListTable.tsx
  src/constants/mock.ts
  src/pages/ian/test.page.tsx
  src/types/dto.ts
Labels: 🚀 feature, 🚨 priority: high

#56 BPS-146/정산 내역 테이블 컴포넌트 제작
  src/components/common/MonthPicker/MonthPickerDropdown.module.scss
  src/components/uploadRevenue/UploadHistoryTable/UploadHistoryTable.tsx
  src/constants/mock.ts
  src/pages/admin/upload-revenue/[[...monthYear]].page.tsx
  src/types/dto.ts
Labels: 🚀 feature

#55 BPS-160/앨범 상세 페이지 UI 제작
  public/images/information.svg
  src/components/album/albumDetailsInformationTooltip/AlbumDetailsInformationTooltip.module.scss
  src/components/album/albumDetailsInformationTooltip/AlbumDetailsInformationTooltip.tsx
  src/components/common/Tooltip/Tooltip.module.scss
  src/components/common/Tooltip/TooltipRoot.tsx
  src/constants/mock.ts
  src/pages/albums/[albumId]/[month]/index.module.scss
  src/pages/albums/[albumId]/[month]/index.page.tsx
Labels: 🚀 feature, 🙏 sorry

#59 BPS-166/앨범 정보 보기 모달 제작
  src/components/common/Modals/Modal.module.scss
  src/components/common/Modals/Modal.tsx
  src/components/dashboard/AlbumInfoModal/AlbumInfoModal.module.scss
  src/components/dashboard/AlbumInfoModal/AlbumInfoModal.tsx
  src/components/dashboard/AlbumInfoModal/TrackListTable/TrackListTable.module.scss
  src/components/dashboard/AlbumInfoModal/TrackListTable/TrackListTable.tsx
  src/constants/mock.ts
  src/pages/ian/test.page.tsx
  src/types/dto.ts
  src/types/enums/modal.enum.ts
Labels: 🚀 feature, ❓question

#60 BPS-164/dashboard chart custom hook 제작
  src/pages/admin/dashboard/[month]/index.page.tsx
  src/services/queries/useDashboardTopFiveRevenueChart.tsx
  src/services/queries/useDashboardTrendsChart.ts
Labels: 🚀 feature

#62 BPS-170/어드민 아티스트 대시보드 페이지 쿼리 훅 통합
  src/pages/admin/dashboard/[month]/index.page.tsx
  src/pages/artist/[artistId]/dashboard/[month]/index.page.tsx
  src/pages/ian/admin/dashboard/[month].page.tsx
  src/pages/ian/albums/[albumId]/dashboard/[month].page.tsx
  src/pages/ian/artist/[artistId]/dashboard/[month].page.tsx
  src/services/queries/dashboard/useDashboardCards.ts
  src/services/queries/dashboard/useDashboardTable.ts
  src/services/queries/dashboard/useDashboardTopFiveRevenueChart.ts
  src/services/queries/dashboard/useDashboardTrendsChart.ts
Labels: 🚀 feature

#63 BPS-172/꺾은 선 차트 쿼리 훅 제작
  src/components/album/AlbumDetailsInformationTooltip/AlbumDetailsInformationTooltip.module.scss
  src/components/album/AlbumDetailsInformationTooltip/AlbumDetailsInformationTooltip.tsx
  src/components/dashboard/AlbumTrendsChart/AlbumTrendsChart.tsx
  src/components/dashboard/MonthlyTrendsChart/MonthlyTrendsChart.tsx
  src/components/dashboard/TopFiveRevenueChart/TopFiveRevenueChart.tsx
  src/pages/albums/[albumId]/[month]/index.page.tsx
  src/pages/ian/albums/[albumId]/dashboard/[month].page.tsx
  src/services/queries/dashboard/useDashboardAlbumTrendsChart.ts
Labels: 🚀 feature

#67 BPS-171/테이블 배경색, 열 너비 스타일링 수정
  src/components/common/Table/Composition/TableCellUI.tsx
  src/components/common/Table/Composition/TableContainerUI.module.scss
  src/components/dashboard/AlbumInfoModal/TrackListTable/TrackListTable.tsx
  src/components/manage-accounts/ArtistAccountsTable/ArtistAccountsTable.tsx
  src/constants/fallbackPageLayout.ts
  src/types/dto.ts
Labels: 🛠️ fix

#64 BPS-148/정산 내역 업로드 커스텀 훅 제작
  src/components/common/ExcelFileUploader/ExcelFileUploader.tsx
  src/components/common/Loading/Loading.module.scss
  src/components/common/Loading/Loading.tsx
  src/components/upload-revenue/UploadHistoryTable/UploadHistoryTable.tsx
  src/pages/admin/upload-revenue/[[...monthYear]].page.tsx
  src/pages/admin/upload-revenue/[month].page.tsx
  src/services/api/upload-revenue/upload-revenue-mock-api.ts
  src/services/queries/upload-revenue/useRevenueUploadHistory.ts
  src/utils/convertYearMonthToQuery.ts
Labels: 🚀 feature, 🙏 sorry

#70 BPS-184/Chip 컴포넌트 UI 개선
  src/components/common/Chip/Chip.module.scss
  src/components/common/Chip/Chip.tsx
  src/components/common/Chip/Chip.utils.ts
  src/utils/formatNumberToKilo.ts
Labels: 🚀 feature, 🛠️ fix

#75 BPS-176/비밀번호 재설정 폼 추가
  src/components/auth/ChangePasswordForm/ChangePasswordForm.module.scss
  src/components/auth/ChangePasswordForm/ChangePasswordForm.tsx
  src/components/auth/ChangePasswordForm/CurrentPasswordForm/CurrentPasswordForm.module.scss
  src/components/auth/ChangePasswordForm/CurrentPasswordForm/CurrentPasswordForm.tsx
  src/components/auth/ChangePasswordForm/NewPasswordForm/NewPasswordForm.tsx
  src/components/my-profile/AdminProfileForm/AdminProfileForm.tsx
  src/components/my-profile/ArtistProfileForm/ArtistProfileForm.tsx
  src/pages/kenny.page.tsx
Labels: 🚀 feature

#65 BPS-173/수록곡 테이블 제작
  public/images/selected.svg
  src/components/album/AlbumTrackListTable/AlbumTrackListTable.module.scss
  src/components/album/AlbumTrackListTable/AlbumTrackListTable.tsx
  src/components/common/Tooltip/Tooltip.module.scss
  src/constants/mock.ts
  src/pages/tony/tony.page.tsx
  src/types/dto.ts
Labels: 🚀 feature

#72 BPS-182/아티스트 현황 페이지 UI 제작
  src/components/artist/ArtistProfileImage/ArtistProfileImage.module.scss
  src/components/artist/ArtistProfileImage/ArtistProfileImage.tsx
  src/components/artist/ArtistsMainLayout/ArtistsMainLayout.module.scss
  src/components/artist/ArtistsMainLayout/ArtistsMainLayout.tsx
  src/components/artist/ArtistsStatusTable/ArtistsStatusTable.module.scss
  src/components/artist/ArtistsStatusTable/ArtistsStatusTable.tsx
  src/components/common/SearchBar/SearchBar.tsx
  src/components/common/Tooltip/Tooltip.module.scss
  src/components/layout/GNB/MobileGNB.tsx
  src/components/layout/GNB/PCGNB.tsx
  src/constants/mock.ts
  src/pages/admin/artists/[month]/index.page.tsx
  src/types/dto.ts
  src/utils/getRandomProfileIndex.ts
Labels: 🚀 feature, 🛠️ fix

#77 BPS-191/페이지 스크롤바 스타일링 & 그에 따른 모달 수정
  src/components/common/Modals/Modal.module.scss
  src/components/common/Modals/Modal.tsx
  src/components/dashboard/AlbumInfoModal/AlbumInfoModal.module.scss
  src/styles/globals.scss
Labels: 🎨 design

#79 BPS-198/기본 프로필 이미지 컴포넌트 제작
  src/components/artist/ArtistProfileImage/ArtistProfileImage.tsx
  src/components/common/DefaultProfileImage/DefaultProfileImage.tsx
  src/components/layout/GNB/MobileGNB.tsx
  src/components/layout/GNB/PCGNB.tsx
Labels: 🚀 feature, ♻️ refactor

#82 BPS-193/모달용 Tooltip 컴포넌트 제작
  src/components/common/Tooltip/ModalTooltip.tsx
  src/components/common/Tooltip/Tooltip.module.scss
  src/components/dashboard/AlbumInfoModal/TrackListTable/TrackListTable.tsx
Labels: 🚀 feature, 🐛 bug

#76 BPS-183/아티스트 현황 fetch 커스텀 훅 제작
  src/components/common/SearchBar/SearchBar.tsx
  src/components/dashboard/TrackStatusTable/AdminTrackStatusTable.tsx
  src/components/dashboard/TrackStatusTable/ArtistTrackStatusTable.tsx
  src/constants/mock.ts
  src/pages/admin/artists/[month]/index.page.tsx
  src/services/api/artists/artists-mock-api.ts
  src/services/queries/artists/useArtistsStatus.ts
  src/utils/convertPageParamToNum.ts
  src/utils/getRandomProfileIndex.ts
  src/utils/updateQueryParam.ts
Labels: 🚀 feature, 🛠️ fix

#80 BPS-200/앨범 리스트 페이지 UI 제작
  src/components/album/AlbumList/AlbumList.module.scss
  src/components/album/AlbumList/AlbumList.tsx
  src/components/album/AlbumListSection/AlbumListSection.module.scss
  src/components/album/AlbumListSection/AlbumListSection.tsx
  src/components/common/AlbumCard/AlbumCard.tsx
  src/components/common/Popover/Popover.tsx
  src/pages/admin/albums/index.page.tsx
Labels: 🚀 feature

#73 BPS-178/드롭다운 컴포넌트 객체 타입 추가
  .env
  src/components/album/AlbumForm/AlbumForm.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/Dropdown.type.ts
  src/components/common/Dropdown/Dropdown.utils.ts
  src/components/common/Dropdown/DropdownList.tsx
  src/components/common/Dropdown/DropdownSelectedValue.tsx
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/Dropdown/DropdownUI.tsx
  src/components/common/Dropdown/DropdownWithSearchBar/DropdownListWithSearchBar.tsx
  src/utils/formatDropdownList.ts
Labels: 🚀 feature, 🛠️ fix, 🙏 sorry

#81 BPS-202/앨범 상세 대시보드 페이지 퍼블리싱
  src/components/album/AlbumDetailsInformationTooltip/AlbumDetailsInformationTooltip.tsx
  src/components/common/Tooltip/Tooltip.module.scss
  src/pages/_document.page.tsx
  src/pages/albums/[albumId]/[month]/index.page.tsx
  src/services/queries/dashboard/useDashboardAlbumInfo.ts
  src/services/queries/dashboard/useDashboardAlbumTrendsChart.ts
Labels: 🚀 feature

#84 BPS-177/어드민, 아티스트 내 프로필 페이지 프로필 조회, 수정 기능 추가
  src/components/auth/ChangePasswordForm/NewPasswordForm/NewPasswordForm.tsx
  src/components/auth/SigninForm/SigninForm.tsx
  src/components/common/Chart/BarChart/BarChart.tsx
  src/components/common/Chart/BarChart/BarChart.utils.ts
  src/components/common/Chart/LineChart/LineChart.tsx
  src/components/common/Chart/LineChart/LineChart.utils.ts
  src/components/common/ImageUploader/ImageUploader.module.scss
  src/components/common/ImageUploader/ImageUploader.tsx
  src/components/common/Inputs/PasswordInput/PasswordField.tsx
  src/components/common/Inputs/TextField/TextField.tsx
  src/components/common/Inputs/TextFieldWithCopy/TextFieldWithCopy.tsx
  src/components/common/Inputs/TextFieldWithUnit/TextFieldWithUnit.tsx
  src/components/common/Loading/Orbit.module.scss
  src/components/common/Loading/Orbit.tsx
  src/components/common/Table/Assemble/AdminAccountsTable.tsx
  src/components/dashboard/AlbumTrendsChart/AlbumTrendsChart.tsx
  src/components/dashboard/MonthlyTrendsChart/MonthlyTrendsChart.tsx
  src/components/layout/GNB/GNB.tsx
  src/components/layout/GNB/MobileGNB.tsx
  src/components/layout/GNB/PCGNB.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Layout.types.ts
  src/components/layout/SideNav/SideNav.tsx
  src/components/manage-accounts/AdminAccountsTable/AdminAccountsTable.tsx
  src/components/my-profile/AdminProfileForm/AdminProfileForm.tsx
  src/components/my-profile/ArtistProfileForm/ArtistProfileForm.tsx
  src/constants/mock.ts
  src/hooks/useInputWithEditMode.ts
  src/pages/admin/albums/new/index.page.tsx
  src/pages/admin/artists/new/index.page.tsx
  src/pages/admin/my-profile/index.module.scss
  src/pages/admin/my-profile/index.page.tsx
  src/pages/albums/[albumId]/[month]/index.page.tsx
  src/pages/artists/[artistId]/dashboard/[month]/index.page.tsx
  src/pages/artists/[artistId]/my-profile/index.module.scss
  src/pages/artists/[artistId]/my-profile/index.page.tsx
  src/pages/ian/albums/[albumId]/dashboard/[month].page.tsx
  src/pages/kenny.page.tsx
  src/pages/signin/index.page.tsx
  src/redux/slices/userSlice.ts
  src/services/api/types/auth.ts
  src/services/queries/my-profile/useUpdateProfile.ts
  src/types/dto.ts
  src/types/enums/user.enum.ts
Labels: 🚀 feature, ♻️ refactor, 🙏 sorry

#87 BPS-212/Axios GET api 함수 제작
  src/constants/mock.ts
  src/services/api/requests/admin/admin.get.api.ts
  src/services/api/requests/albums/albums.get.api.ts
  src/services/api/requests/artist/artist.get.api.ts
  src/services/api/requests/transaction/transaction.get.api.ts
  src/services/api/types/admin.ts
  src/services/api/types/artist.ts
  src/services/api/types/transaction.ts
  src/services/api/upload-revenue/upload-revenue-mock-api.ts
  src/services/queries/upload-revenue/useRevenueUploadHistory.ts
  src/types/dto.ts
Labels: 🚀 feature

#88 BPS-214/대시보드 리팩토링 (자잘한 컨벤션 준수 & SSR 실행조건 추가 & 페이지네이션 prefetch 로직)
  src/pages/_app.page.tsx
  src/pages/admin/dashboard/[month]/index.module.scss
  src/pages/admin/dashboard/[month]/index.page.tsx
  src/pages/admin/upload-revenue/[month].page.tsx
  src/pages/albums/[albumId]/[month]/index.page.tsx
  src/pages/artists/[artistId]/dashboard/[month]/index.page.tsx
  src/pages/ian/admin/dashboard/[month].page.tsx
  src/pages/ian/albums/[albumId]/dashboard/[month].page.tsx
  src/pages/ian/artist/[artistId]/dashboard/[month].page.tsx
  src/services/queries/artists/useArtistsStatus.ts
  src/services/queries/dashboard/queryFns/albumInfo.ts
  src/services/queries/dashboard/queryFns/albumTrendsChart.ts
  src/services/queries/dashboard/queryFns/cards.ts
  src/services/queries/dashboard/queryFns/table.ts
  src/services/queries/dashboard/queryFns/topFiveRevenueChart.ts
  src/services/queries/dashboard/queryFns/trendsChart.ts
  src/services/queries/dashboard/useAdminDashboard.ts
  src/services/queries/dashboard/useAlbumDashboard.ts
  src/services/queries/dashboard/useArtistDashboard.ts
  src/services/queries/dashboard/useDashboardAlbumInfo.ts
  src/services/queries/dashboard/useDashboardAlbumTrendsChart.ts
  src/services/queries/manage-accounts/useAccounts.ts
  src/services/queries/upload-revenue/useRevenueUploadHistory.ts
  src/services/queries/useDashboardTopFiveRevenueChart.tsx
  src/services/queries/useDashboardTrendsChart.ts
  src/utils/test.utils.tsx
Labels: 🚀 feature, 🛠️ fix, ♻️ refactor, ❓question

#86 BPS-208/앨범 상세 > 수정 페이지 퍼블리싱
  public/images/default-album-cover-small.png
  src/components/album/AlbumTrackListTable/AlbumTrackListTable.tsx
  src/components/common/ImageUploader/ImageUploader.tsx
  src/pages/albums/[albumId]/edit/index.module.scss
  src/pages/albums/[albumId]/edit/index.page.tsx
Labels: 🚀 feature

#78 BPS-195/redux persist 추가
  package.json
  src/middleware.page.ts
  src/pages/_app.page.tsx
  src/pages/admin/dashboard/[month]/index.page.tsx
  src/redux/slices/userSlice.ts
  src/redux/store.ts
  src/services/queries/auth/useSignin.ts
  src/types/middleware.type.ts
  src/utils/withAuthorityCheck.ts
  yarn.lock
Labels: 🚀 feature, 🙏 sorry

#94 BPS-248/앨범 카드 - 상세 링크 & 수정 링크 수정
  src/components/album/AlbumList/AlbumList.tsx
  src/components/album/AlbumListSection/AlbumListSection.tsx
  src/components/common/AlbumCard/AlbumCard.tsx
  src/components/common/AlbumCard/OptionsButton.tsx
Labels: 🛠️ fix

#89 BPS-211/side nav active 기능 추가
  src/components/layout/SideNav/SideNav.module.scss
  src/components/layout/SideNav/SideNav.tsx
  src/components/layout/SideNav/SideNav.type.ts
  src/components/layout/SideNav/SideNav.util.ts
  src/components/layout/SideNav/SideNavMobile.tsx
  src/constants/sidenavList.ts
  src/utils/isFormatYearMonth.ts
Labels: 🚀 feature, 🙏 sorry

#92 BPS-245/getServerSideProps의 query 타입 선언
  src/pages/admin/artists/[month]/index.page.tsx
  src/pages/admin/dashboard/[month]/index.page.tsx
  src/pages/admin/manage-accounts/index.page.tsx
  src/pages/admin/upload-revenue/[month].page.tsx
  src/pages/albums/[albumId]/[month]/index.page.tsx
  src/pages/artists/[artistId]/dashboard/[month]/index.page.tsx
Labels: ♻️ refactor

#97 BPS-251/sidenav custom hook 제작
  src/components/layout/Layout.tsx
  src/components/layout/Layout.types.ts
  src/components/layout/SideNav/SideNav.tsx
  src/hooks/useSideNavList.ts
Labels: 🐛 bug

#98 BPS-252/차트 유틸 함수 추가 및 convertYearMonthToQuery 함수 삭제
  src/pages/admin/artists/[month]/index.page.tsx
  src/pages/admin/upload-revenue/[month].page.tsx
  src/services/api/artists/artists-mock-api.ts
  src/services/api/requests/admin/admin.get.api.ts
  src/services/api/requests/albums/albums.get.api.ts
  src/services/api/requests/artist/artist.get.api.ts
  src/services/api/requests/transaction/transaction.get.api.ts
  src/services/queries/dashboard/queryFns/topFiveRevenueChart.ts
  src/utils/subtractMonths.ts
Labels: 🚀 feature, 🐛 bug

#95 BPS-213/앨범 상세 > 수정 페이지에 수록곡 추가 기능 추가
  src/components/album/AddTrackModal/AddTrackForm.module.scss
  src/components/album/AddTrackModal/AddTrackForm.tsx
  src/components/album/AddTrackModal/AddTrackModal.tsx
  src/components/album/AlbumForm/AlbumForm.tsx
  src/components/common/Dropdown/Dropdown.type.ts
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/ImageUploader/ImageUploader.tsx
  src/components/common/Inputs/InputLayout.module.scss
  src/components/common/Inputs/InputLayout.tsx
  src/components/common/Inputs/TextField/TextField.tsx
  src/components/common/Inputs/TextFieldWithUnit/TextFieldWithUnit.tsx
  src/components/common/Loading/Orbit.module.scss
  src/components/common/Loading/Orbit.tsx
  src/constants/artists.ts
  src/pages/admin/albums/[albumId]/edit/index.module.scss
  src/pages/admin/albums/[albumId]/edit/index.page.tsx
  src/pages/albums/[albumId]/edit/index.module.scss
  src/pages/albums/[albumId]/edit/index.page.tsx
  src/services/api/types/albums.ts
  src/services/queries/albums/useAddAlbumTrack.ts
  src/services/queries/albums/useAlbumInfo.ts
  src/services/queries/albums/useUpdateAlbumInfo.ts
  src/types/album.types.ts
  src/utils/formatDropdownList.ts
Labels: 🚀 feature, 🙏 sorry

#102 BPS-250/대시보드 api 연동
  src/components/artist/ArtistsStatusTable/ArtistsStatusTable.tsx
  src/components/common/Chart/BarChart/BarChart.tsx
  src/components/common/Chart/BarChart/BarChart.utils.ts
  src/components/common/Chart/DoughnutChart/DoughnutChart.tsx
  src/components/common/Chart/DoughnutChart/DoughnutChart.utils.ts
  src/components/common/Chart/LineChart/LineChart.tsx
  src/components/common/CustomLegend/CustomLegend.module.scss
  src/components/common/SearchBar/SearchBar.tsx
  src/components/dashboard/AlbumInfoModal/AlbumInfoModal.tsx
  src/components/dashboard/AlbumTrendsChart/AlbumTrendsChart.tsx
  src/components/dashboard/MonthlyTrendsChart/MonthlyTrendsChart.tsx
  src/components/dashboard/TopFiveRevenueChart/TopFiveRevenueChart.module.scss
  src/components/dashboard/TopFiveRevenueChart/TopFiveRevenueChart.tsx
  src/components/dashboard/TopFiveRevenueChart/TopFiveRevenueChartLegend.tsx
  src/components/dashboard/TrackStatusTable/AdminTrackStatusTable.tsx
  src/components/dashboard/TrackStatusTable/ArtistTrackStatusTable.tsx
  src/components/dashboard/TrackStatusTable/EmptyTableData.tsx
  src/components/layout/SideNav/SideNav.util.ts
  src/constants/mock.ts
  src/pages/admin/artists/[month]/index.page.tsx
  src/pages/admin/dashboard/[month]/index.module.scss
  src/pages/admin/dashboard/[month]/index.page.tsx
  src/pages/albums/[albumId]/[month]/index.module.scss
  src/pages/albums/[albumId]/[month]/index.page.tsx
  src/pages/artists/[artistId]/dashboard/[month]/index.module.scss
  src/pages/artists/[artistId]/dashboard/[month]/index.page.tsx
  src/services/api/requests/albums/albums.get.api.ts
  src/services/api/requests/artist/artist.get.api.ts
  src/services/api/types/albums.ts
  src/services/api/types/artist.ts
  src/services/queries/dashboard/queryFns/albumInfo.ts
  src/services/queries/dashboard/queryFns/albumTrendsChart.ts
  src/services/queries/dashboard/queryFns/cards.ts
  src/services/queries/dashboard/queryFns/table.ts
  src/services/queries/dashboard/queryFns/topFiveRevenueChart.ts
  src/services/queries/dashboard/queryFns/trendsChart.ts
  src/services/queries/dashboard/useAdminDashboard.ts
  src/services/queries/dashboard/useAlbumDashboard.ts
  src/services/queries/dashboard/useArtistDashboard.ts
  src/types/dto.ts
  src/utils/subtractMonths.ts
Labels: 🚀 feature

#105 BPS-265/계정관리 페이지 api 연동
  src/pages/admin/manage-accounts/index.module.scss
  src/pages/admin/manage-accounts/index.page.tsx
  src/services/queries/manage-accounts/useAccounts.ts
Labels: 🚀 feature

#109 BPS-266/아티스트 현황 api 연동 & 자잘한 버그 픽스
  src/components/album/AlbumListSection/AlbumListSection.module.scss
  src/components/album/AlbumListSection/AlbumListSection.tsx
  src/components/artist/ArtistsStatusTable/ArtistsStatusTable.tsx
  src/components/artist/ArtistsStatusTable/EmptyArtistTableData.module.scss
  src/components/artist/ArtistsStatusTable/EmptyArtistTableData.tsx
  src/components/common/Chart/DoughnutChart/DoughnutChart.utils.ts
  src/components/common/Dropdown/DropdownUI.module.scss
  src/components/common/ProgressBar/ProgressBar.tsx
  src/components/dashboard/AlbumInfoModal/AlbumInfoModal.tsx
  src/components/dashboard/TopFiveRevenueChart/TopFiveRevenueChartLegend.tsx
  src/components/dashboard/TrackStatusTable/AdminTrackStatusTable.tsx
  src/components/dashboard/TrackStatusTable/ArtistTrackStatusTable.tsx
  src/components/dashboard/TrackStatusTable/EmptyTrackTableData.module.scss
  src/components/dashboard/TrackStatusTable/EmptyTrackTableData.tsx
  src/components/layout/FallbackPageLayout.module.scss
  src/components/layout/GNB/GNB.tsx
  src/components/layout/GNB/MobileGNB.tsx
  src/components/layout/GNB/PCGNB.tsx
  src/components/layout/SideNav/SideNav.util.ts
  src/constants/artists.ts
  src/constants/queryKeys.ts
  src/constants/table.ts
  src/pages/admin/albums/[albumId]/edit/index.page.tsx
  src/pages/admin/artists/[month]/index.page.tsx
  src/pages/admin/manage-accounts/index.module.scss
  src/services/api/albums/albums-mock-api.tsx
  src/services/api/artists/artists-mock-api.ts
  src/services/queries/albums/useCreateAlbum.ts
  src/services/queries/artists/useArtistsStatus.ts
  src/services/queries/artists/useCreateArtist.ts
  src/services/queries/useTest.ts
Labels: 🚀 feature, 🐛 bug

#108 BPS-261/잘못된 파일 확장자일 때 AlertModal 연결
  src/components/common/ExcelFileUploader/ExcelFileUploader.tsx
  src/components/common/Modals/AlertModal/AlertModal.module.scss
Labels: 🚀 feature
