Repository Bluekey-Payment-System/BPS-FE, pull requests merged in 2023-11, with the labels that each got.

#125 BPS-381/어드민 권한 요청 대기, 거절 페이지 연동
  src/components/layout/Layout.tsx
  src/pages/_app.page.tsx
  src/pages/admin/pending/index.page.tsx
  src/pages/admin/rejected/index.page.tsx
  src/pages/admin/signin/pending/index.page.tsx
  src/pages/admin/signin/rejected/index.page.tsx
  src/pages/albums/[albumId]/[month]/index.page.tsx
  src/pages/artists/[artistId]/dashboard/[month]/index.page.tsx
  src/services/api/requests/notification-controller/notification-controller.post.api.ts
  src/services/api/requests/requests.api.ts
  src/services/api/types/auth.ts
  src/services/queries/auth/useSignin.ts
  src/services/queries/dashboard/useAlbumDashboard.ts
  src/services/queries/manage-accounts/useAccounts.ts
  src/services/queries/my-profile/useUpdateProfile.ts
  src/services/queries/notification-controller/useRequestAuthorities.ts
  src/types/dto.ts
  src/types/enums/user.enum.ts
  src/utils/getErrorModalInfo.ts
Labels: 🚀 feature

#127 BPS-376/정렬, 필터 기능 구현
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Filter/Filter.tsx
  src/components/common/Filter/Filter.type.ts
  src/components/common/Filter/FilterForm/FilterForm.tsx
  src/components/common/Filter/FilterForm/MultiRangeSlider.tsx
  src/components/common/Filter/FilterForm/MultiRangeSlider.type.ts
  src/components/dashboard/TrackStatusTable/AdminTrackStatusTable.tsx
  src/components/dashboard/TrackStatusTable/ArtistTrackStatusTable.tsx
  src/constants/trackStatusTable.ts
  src/pages/admin/dashboard/[month]/index.page.tsx
  src/pages/artists/[artistId]/dashboard/[month]/index.page.tsx
  src/services/api/requests/admin/admin.get.api.ts
  src/services/api/requests/artist/artist.get.api.ts
  src/services/queries/dashboard/queryFns/table.ts
  src/services/queries/dashboard/useAdminDashboard.ts
  src/services/queries/dashboard/useArtistDashboard.ts
Labels: 🚀 feature

#130 BPS-385/아티스트 추가, 삭제 시 아티스트 현황과 타 계정관리 쿼리에 반영
  src/services/queries/artists/useCreateArtist.ts
  src/services/queries/manage-accounts/useWithdrawMember.ts
Labels: 🐛 bug

#131 BPS-384/API 호출 간 검색어 쿼리에 encoding 처리
  src/pages/admin/albums/index.page.tsx
  src/pages/admin/artists/[month]/index.page.tsx
  src/pages/artists/[artistId]/albums/index.page.tsx
  src/services/api/requests/admin/admin.get.api.ts
  src/services/api/requests/albums/albums.get.api.ts
  src/services/api/requests/artist/artist.get.api.ts
  src/services/queries/albums/useAlbumList.ts
  src/services/queries/artists/useArtistsStatus.ts
  src/services/queries/dashboard/queryFns/table.ts
Labels: 🐛 bug

#133 BPS-389/필터 초기화 기능 구현
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Filter/FilterForm/FilterForm.module.scss
  src/components/common/Filter/FilterForm/FilterForm.tsx
  src/components/common/Filter/FilterForm/MultiRangeSlider.tsx
Labels: 🚀 feature

#132 BPS-383/앨범 수정 기능 추가
  src/components/album/AddTrackModal/AddTrackForm.tsx
  src/components/album/AlbumForm/AlbumForm.tsx
  src/components/album/AlbumTrackListTable/AlbumTrackListTable.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/constants/mock.ts
  src/pages/admin/albums/[albumId]/edit/index.page.tsx
  src/services/api/requests/albums/albums.patch.api.ts
  src/services/api/types/albums.ts
  src/services/queries/albums/useAlbumInfo.ts
  src/services/queries/albums/useUpdateAlbumInfo.ts
  src/types/dto.ts
Labels: 🚀 feature, 🙏 sorry
